AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions IAM Role for QA environment

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub org or username
  GitHubRepo:
    Type: String
    Description: GitHub repository name

Resources:
  GitHubActionsDevRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-qa
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:environment:qa

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

Outputs:
  DevRoleArn:
    Value: !GetAtt GitHubActionsDevRole.Arn
