name: Deploy to QA

on:
  push:
    branches:
      - qa

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    environment: qa

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-qa
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: QA deployment
        run: echo "Deploying to QA"
